Better ejection
thedropbears/pyrapidreact pull request #157
Opened 2022-03-26 11:53 UTC by OliverW10

ejects opponent balls out of the shooter at a low speed if it can. This is to prevent the large disruption caused by picking up an opponent ball and having to eject it out the intake, making us unable to intake for a second or two.

2022-03-26 13:34 UTC, auscompgeek commented on controllers/shooter.py
>      _wants_to_fire = will_reset_to(False)
What happens if both of these are true?

I think that is probably undesirable, and we should make that state impossible. For example we could have an enum of possible commands for the shooter.

2022-03-28 03:37 UTC, james-ward commented
This is a major departure from the strategy that we all agreed upon. As such, perhaps we should consider what it actually looks like in detail.

For example, if we pick up an opponent ball and spit it out the turret like this, we might infer that we are chewing through a big patch of balls that we can't easily separate. Maybe the intake shouldn't retract if the colour is wrong and it is being ejected through the shooter so that we can keep going until we get our coloured ball?

If we are picking up a ball to catflap, that's more deliberate, so the intake probably should come back up.

Thoughts?

2022-03-28 08:39 UTC, OliverW10 commented
Yes, this and the ability to toggle auto-retract I added in #139 go hand in hand. I think the auto-retract is only useful situationally (e.g. picking up against walls where you dont have a clear view or when under heavy defense) but otherwise I think raising the intake should be up to driver input.
With auto retract off it will still stop the intake motor running when we have a ball in the tunnel and if it needs to eject it out the front it will raise intake.

2022-03-28 09:33 UTC, james-ward commented
Could we come up with a compromise here? I really don't like leaving the intake down all the time because every foul for breaching another robot's frame perimeter costs us the same as two cargo, and if we lose the intake, we are knackered.

How about this (which I think fits nicely with this new clearing approach):
The auto retract only happens when we have two cargo on board. The opposition cargo would be ejected and the intake stays down, but once we have two we get the intake out the way. If the driver is in the corner looking to fill up, the intake will stay down until they have a full load, or they pull it up after one.

2022-03-28 09:41 UTC, james-ward commented
Another option would be to not have the override be a toggle, but make a button press be auto retract on each correct ball (stay down for rejections) and holding the button down be "keep it down until full" mode.

2022-03-28 11:40 UTC, james-ward requested changes

2022-03-28 11:40 UTC, james-ward commented on controllers/indexer.py
> +            self.next_state("stopped")
Will this cause it to never clear through the shooter?
 * Initial call happens
 * Shooter controller set to clear -> this just sets a private flag in the controller
 * Lines 97-100 check the state of the shooter controller, but it hasn't changed yet, so the indexer moves to the `stopped` state

2022-03-28 11:42 UTC, james-ward commented
Could this be approached differently? From the indexer point of view, clearing through the shooter is the same as firing. So why not keep the states essentially the same, just have a way to override the shooter setpoint speed to the low dribble-it-out speed.

2022-03-28 11:47 UTC, james-ward commented
And as I look at all this stuff and think about how the indexer state machine works and how it transfers cargo, I'm now convinced that having a driver override for the intake staying down and turning is a recipe for disaster. The potential to end up with two cargo in the same segment of the indexer is too much. At the very least the intake wheels need to be stopped until the cargo has been moved out of the tunnel and into the chimney.

2022-03-28 12:19 UTC, auscompgeek commented
> The auto retract only happens when we have two cargo on board.

I think we might want to have have two auto-retract modes then:

- Auto retract once we have two cargo, like you suggest. This can be used when we explicitly want to pick up two cargo.
- Auto retract whenever we pick up cargo (like the robot current does). Particularly useful when we anticipate heavy defence, or we don't have a clear view of the robot.

Obviously, these two modes would be equivalent once we cat-flap a cargo.

> The opposition cargo would be ejected and the intake stays down

In our testing on Saturday, we found that the intake needs to be raised before we can spit a ball back out the intake.

> Another option would be to not have the override be a toggle, but make a button press be auto retract on each correct ball (stay down for rejections) and holding the button down be "keep it down until full" mode.

I definitely think holding the button down to activate is a good idea. Makes it almost impossible for the person to forget it's active.

2022-03-28 22:28 UTC, OliverW10 commented
This is the logic i've implemented (if i haven't made a mistake)
 - Thumb button toggles intake, if its down it will retract with any ball
 - Holding button 11 is the 'intake untill full' button, it will keep intake down until it has two balls
 - If there is a ball in the tunnel, intake motor stops, regardless of mode
 - If there is no ball in the chimney and we have an opponent ball it ejects it out the turret
 - If we eject out of the intake it will raise it first

2022-03-28 22:40 UTC, james-ward commented
@OliverW10 take a look at #169 for what I think is a nicer way to do the turret rejection bit. Doesn't require changing the indexer state machine states at all.

2022-03-29 00:03 UTC, OliverW10 commented
Ive also cleaned up the logic in the reading state

2022-03-29 00:15 UTC, james-ward commented
This looks good, but we still need to stop the intake rollers when the auto retract is off and we are processing a ball. We cannot allow two balls into the indexer tunnel at the same time.
Same applies to rejecting a ball through the intake with it down - will need to be back driven.

2022-03-29 00:22 UTC, OliverW10 commented
[the intake rollers stop if there is a ball in the tunnel](https://github.com/thedropbears/pyrapidreact/pull/157/files#diff-a06acd8fb6a9bd3deaa5ec37eba793f8d165afeceb31ab4444018e4cb01b86f5R195) and the [clearing through intake raises intake](https://github.com/thedropbears/pyrapidreact/pull/157/files#diff-1286f76b84283522f93636b5c521e8381f64c5149449c8259df139708160d10eR89), should I make it backdrive intake instead?

2022-03-29 00:25 UTC, james-ward commented
I think so. Isn't the idea here to try to save time, which the intake raising and lowering is the biggest time sink. And if the driver is holding the intake down, shouldn't we keep it down even for a rejection?
If we want to raise it regardless when we reject that's fine by me. I just want to be sure that we don't end up in a race condition between the driver inputs and the state machine.

2022-03-29 00:27 UTC, james-ward commented
And the reason I didn't see the motor being stopped is that we now have intake operational logic in robot.py
This has become complex enough that I don't think that's appropriate any more.

2022-03-29 01:43 UTC, OliverW10 commented
I've made it so intake backdrives and also changed where intake is controlled

2022-03-29 02:20 UTC, james-ward approved these changes
lgtm
@auscompgeek

2022-03-29 23:06 UTC, merged