colour sensor consistency
thedropbears/pyrapidreact pull request #83
Opened 2022-03-03 07:35 UTC by LucienMorey

allow colour sensor enum to keep rolling tally of colour values when it sees a ball to increase its confidence over longer periods

2022-03-03 09:13 UTC, auscompgeek requested changes
If we're really going to go down the path of rolling totals of colour readings (which I'm still unconvinced is a good idea), then I'd like to see this API:

```
Indexer
+ get_colour() : CargoColour
+ reset_colour_reading() : None
```

where `CargoColour` is the existing enum with the `match_colour` method removed.

I won't dictate how the colour matching is implemented, but it should be considered an implementation detail to the controller, outside from that reset method (i.e. even the mere fact that it might be a separate object should be hidden from the controller).

2022-03-03 09:13 UTC, auscompgeek commented on components/indexer.py
> +    cargo_colour = CargoColour()
Do not assign mutable objects to a class variable that are supposed to be defaults. Class variables are global state. Expect things to break badly once RobotPy has tests again.

2022-03-04 01:06 UTC, james-ward commented
Hey @auscompgeek if you want to change the colour matching method that would be great. Yesterday we had some false identifications (which may have been caused by crap on the sensor) but we are worried that the current method of just looking at the last colour identification is unreliable. The last identification has the possibility of being one where the cargo is right on the limit of identification, meaning a false identification is more likely. Hence the move to keeping a running total - an unreliable reading at the end won't swamp the accumulated good readings.

If this is something you think we can do with the `rev.ColorMatch` then that's great too. But we need to fix this pronto, hence Lucien getting something written that seems to be working.

2022-03-04 01:49 UTC, auscompgeek commented
> Hence the move to keeping a running total - an unreliable reading at the end won't swamp the accumulated good readings.

Did we consider taking multiple readings and taking the most common valid reading to deal with this instead?

2022-03-04 09:11 UTC, auscompgeek approved these changes
LGTM, a couple of minor comments.

2022-03-04 09:11 UTC, auscompgeek commented on components/indexer.py
> +            return CargoColour.RED
We'll get here if `red_total == blue_total`. Is this intended?

2022-03-04 09:11 UTC, auscompgeek commented on components/indexer.py
> +        elif wpilib.DriverStation.getAlliance() is wpilib.DriverStation.Alliance.kRed:
pybind11 enums are weird :(
```suggestion
        if wpilib.DriverStation.getAlliance() == wpilib.DriverStation.Alliance.kBlue:
            return self.red_total > self.blue_total
        elif wpilib.DriverStation.getAlliance() == wpilib.DriverStation.Alliance.kRed:
```
although we could just do away with this altogether?

2022-03-05 00:27 UTC, merged